/**
 * build.js — Standalone Bundler & Packaging Script for FillX Content Script
 *
 * Combines modular content script files into a clean, standalone, browser-executable
 * bundle (dist/contentScript.bundle.js) suitable for Manifest V3 content_scripts.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, 'src');
const distDir = path.join(__dirname, 'dist');

if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// Ordered sequence of modules to combine for the standalone content script bundle
const modules = [
  'shared/messageTypes.js',
  'content/fieldIdentifier.js',
  'content/fieldDetector.js',
  'content/valueSetter.js',
  'content/highlighter.js',
  'content/fieldState.js',
  'content/savePromptBridge.js',
  'content/openEndedGenerator.js',
  'content/dynamicObserver.js',
  'content/autofillEngine.js',
  'content/contentScript.js',
];

let bundleContent = `/**
 * FillX Extension — Content Script Standalone Production Bundle
 * Auto-generated by build.js. Combines all DOM scanning, autofill, and highlighting modules.
 */
(() => {
  'use strict';
`;

for (const relPath of modules) {
  const filePath = path.join(srcDir, relPath);
  if (!fs.existsSync(filePath)) {
    console.error(`Error: Missing source file ${filePath}`);
    process.exit(1);
  }

  let code = fs.readFileSync(filePath, 'utf8');

  // Strip ES module import and export statements for IIFE compilation
  code = code
    .replace(/^\s*import\s+[^;]+;\s*$/gm, '')
    .replace(/^\s*export\s+(const|let|var|function|class)\s+/gm, '$1 ')
    .replace(/^\s*export\s+default\s+/gm, '')
    .replace(/^\s*export\s*\{[^}]*\};?\s*$/gm, '');

  bundleContent += `\n  // ─── Module: ${relPath} ───\n`;
  bundleContent += code + '\n';
}

bundleContent += `
})();
`;

// Write to dist/contentScript.bundle.js
fs.writeFileSync(path.join(distDir, 'contentScript.bundle.js'), bundleContent, 'utf8');

// Copy CSS to dist/
const cssPath = path.join(srcDir, 'content', 'highlighter.css');
if (fs.existsSync(cssPath)) {
  fs.copyFileSync(cssPath, path.join(distDir, 'highlighter.css'));
}

console.log('✓ FillX Content Script bundled successfully to dist/contentScript.bundle.js');
console.log('✓ Highlighter CSS copied to dist/highlighter.css');
