/**
 * build.js — Standalone Bundler for FillX Content Script
 * Run: node build.js
 * Then: npx vite build  (builds the React popup)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, 'src');
const distDir = path.join(__dirname, 'dist');

if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

const modules = [
  'shared/messageTypes.js',
  'shared/fieldValueValidator.js',
  'shared/answerGenerator.js',
  'content/fieldIdentifier.js',
  'content/fieldDetector.js',
  'content/valueSetter.js',
  'content/highlighter.js',
  'content/fieldState.js',
  'content/savePromptBridge.js',
  'content/openEndedGenerator.js',
  'content/dynamicObserver.js',
  'content/autofillEngine.js',
  'content/contentScript.js',
];

let bundle = `/**
 * FillX Content Script Bundle — Auto-generated by build.js
 */
(() => {
  'use strict';
`;

for (const relPath of modules) {
  const filePath = path.join(srcDir, relPath);
  if (!fs.existsSync(filePath)) {
    console.error(`❌ Missing: ${filePath}`);
    process.exit(1);
  }

  let code = fs.readFileSync(filePath, 'utf8');
  code = code
    .replace(/^\s*import\s+[^;]+;\s*$/gm, '')
    .replace(/^\s*export\s+(const|let|var|function|class|async\s+function)\s+/gm, '$1 ')
    .replace(/^\s*export\s+default\s+/gm, '')
    .replace(/^\s*export\s*\{[^}]*\};?\s*$/gm, '');

  bundle += `\n  // ─── ${relPath} ───\n${code}\n`;
}

bundle += `\n})();\n`;

fs.writeFileSync(path.join(distDir, 'contentScript.bundle.js'), bundle, 'utf8');

const cssPath = path.join(srcDir, 'content', 'highlighter.css');
if (fs.existsSync(cssPath)) {
  fs.copyFileSync(cssPath, path.join(distDir, 'highlighter.css'));
}

const bundleSize = (fs.statSync(path.join(distDir, 'contentScript.bundle.js')).size / 1024).toFixed(1);
console.log(`✓ contentScript.bundle.js (${bundleSize}KB)`);
console.log(`✓ highlighter.css`);
console.log(`\n✅ Content script build complete.`);
console.log(`   Next: run \`npx vite build\` to build the React popup.\n`);
